<?
require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
$APPLICATION->SetTitle("Отзывы");
?>

<? $APPLICATION->IncludeComponent(
	"bitrix:news.list",
	"reviews",
	[
		"COMPONENT_TEMPLATE"              => ".default",
		"IBLOCK_TYPE"                     => "info",
		"IBLOCK_ID"                       => "8",
		"NEWS_COUNT"                      => "20",
		"SORT_BY1"                        => "ACTIVE_FROM",
		"SORT_ORDER1"                     => "DESC",
		"SORT_BY2"                        => "SORT",
		"SORT_ORDER2"                     => "ASC",
		"FILTER_NAME"                     => "",
		"FIELD_CODE"                      => [
			0 => "NAME",
			1 => "PREVIEW_TEXT",
			2 => "",
		],
		"PROPERTY_CODE"                   => [
			0 => "USER_ID",
			1 => "",
		],
		"CHECK_DATES"                     => "Y",
		"DETAIL_URL"                      => "",
		"AJAX_MODE"                       => "N",
		"AJAX_OPTION_JUMP"                => "N",
		"AJAX_OPTION_STYLE"               => "Y",
		"AJAX_OPTION_HISTORY"             => "N",
		"AJAX_OPTION_ADDITIONAL"          => "",
		"CACHE_TYPE"                      => "A",
		"CACHE_TIME"                      => "36000000",
		"CACHE_FILTER"                    => "N",
		"CACHE_GROUPS"                    => "Y",
		"PREVIEW_TRUNCATE_LEN"            => "",
		"ACTIVE_DATE_FORMAT"              => "d.m.Y",
		"SET_TITLE"                       => "Y",
		"SET_BROWSER_TITLE"               => "Y",
		"SET_META_KEYWORDS"               => "Y",
		"SET_META_DESCRIPTION"            => "Y",
		"SET_LAST_MODIFIED"               => "N",
		"INCLUDE_IBLOCK_INTO_CHAIN"       => "Y",
		"ADD_SECTIONS_CHAIN"              => "Y",
		"HIDE_LINK_WHEN_NO_DETAIL"        => "N",
		"PARENT_SECTION"                  => "",
		"PARENT_SECTION_CODE"             => "",
		"INCLUDE_SUBSECTIONS"             => "Y",
		"STRICT_SECTION_CHECK"            => "N",
		"DISPLAY_DATE"                    => "Y",
		"DISPLAY_NAME"                    => "Y",
		"DISPLAY_PICTURE"                 => "Y",
		"DISPLAY_PREVIEW_TEXT"            => "Y",
		"PAGER_TEMPLATE"                  => ".default",
		"DISPLAY_TOP_PAGER"               => "N",
		"DISPLAY_BOTTOM_PAGER"            => "Y",
		"PAGER_TITLE"                     => "Новости",
		"PAGER_SHOW_ALWAYS"               => "N",
		"PAGER_DESC_NUMBERING"            => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL"                  => "N",
		"PAGER_BASE_LINK_ENABLE"          => "N",
		"SET_STATUS_404"                  => "N",
		"SHOW_404"                        => "N",
		"MESSAGE_404"                     => ""
	],
	false
); ?>

<? $APPLICATION->IncludeComponent(
	"dial:iblock.element.add.form",
	"reviews_add",
	[
		"AJAX_MODE"                     => "Y",
		"AJAX_OPTION_JUMP"              => "N",
		"COMPOSITE_FRAME_MODE"          => "A",
		"COMPOSITE_FRAME_TYPE"          => "AUTO",
		"CUSTOM_TITLE_DATE_ACTIVE_FROM" => "",
		"CUSTOM_TITLE_DATE_ACTIVE_TO"   => "",
		"CUSTOM_TITLE_DETAIL_PICTURE"   => "",
		"CUSTOM_TITLE_DETAIL_TEXT"      => "",
		"CUSTOM_TITLE_IBLOCK_SECTION"   => "",
		"CUSTOM_TITLE_NAME"             => "",
		"CUSTOM_TITLE_PREVIEW_PICTURE"  => "",
		"CUSTOM_TITLE_PREVIEW_TEXT"     => "",
		"CUSTOM_TITLE_TAGS"             => "",
		"DEFAULT_INPUT_SIZE"            => "30",
		"DETAIL_TEXT_USE_HTML_EDITOR"   => "N",
		"ELEMENT_ASSOC"                 => "CREATED_BY",
		"GROUPS"                        => [
			0 => "2",
		],
		"IBLOCK_ID"                     => "8",
		"IBLOCK_TYPE"                   => "info",
		"LEVEL_LAST"                    => "Y",
		"LIST_URL"                      => "",
		"MAX_FILE_SIZE"                 => "0",
		"MAX_LEVELS"                    => "100000",
		"MAX_USER_ENTRIES"              => "100000",
		"PREVIEW_TEXT_USE_HTML_EDITOR"  => "N",
		"PROPERTY_CODES"                => [
			0 => "257",
			1 => "NAME",
			2 => "PREVIEW_TEXT",
		],
		"PROPERTY_CODES_REQUIRED"       => [
			0 => "257",
			1 => "NAME",
			2 => "PREVIEW_TEXT",
		],
		"RESIZE_IMAGES"                 => "N",
		"SEF_MODE"                      => "N",
		"STATUS"                        => "ANY",
		"STATUS_NEW"                    => "NEW",
		"SUBMIT_NAME"                   => "reviews_add",
		"USER_MESSAGE_ADD"              => "",
		"USER_MESSAGE_EDIT"             => "",
		"USE_CAPTCHA"                   => "N",
		"COMPONENT_TEMPLATE"            => "reviews_add"
	],
	false
); ?>

<? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php"); ?>